### ISSUE TITLE
Settings page. 

### ISSUE THREAD

**Issue by tasomaniac** [tasomaniac/OpenLinkWith#4]
Settings page will include 

- [x] Tutorial and Information about the app. #10 
- [x] List of preferred Activities and ability to reset them. #9 
- [x] Request access to the usage stats. #11
